config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'about#index'

  get 'home/index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/home/index.html.erb
<!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
          </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mybootstrap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

  <body>
    
    <nav class="navbar navbar-inverse">
        <div class="container">
        	<ul class="nav navbar-nav">
        		<li><%= link_to "Home", root_path %></li>
        		<li><%= link_to "About", about_path %></li>
      	  	</ul>
        <form class="navbar-form navbar-right" role ="form">
          <div class="form-group">
          	<input type="text" placeholder="Email" class="form-control">
          </div>
          <div class="form-group">
          	<input type="password" placeholder="Password" class="form-control">
          </div>
          <button type="submit" class="btn btn-sucess">Sign in</button>
        </form>
      </div>
    </nav>

    <%= render 'partials/jumbotron' %>
    
    <main role="main">


      <div class="container">
        <%= yield %>

        <hr>

      </div> <!-- /container -->

    </main>

    <%= render 'partials/footer' %>
    
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="container">
      <p>&copy; UnB FGA 2017</p>
</footer>

app/views/partials/_jumbotron.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<% if params[:controller] == 'home' %>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Hello, world!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
      </div>
<% end %>